---
###############################################################################
# Manager ACME Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   acme_user: string acme username.
#   acme_group: string acme group.
#   acme_create_user: boolean true to create role default user.
#   acme_default_user: dict containing builitin.user options for acme.
#   acme_default_group: dict containing builitin.group options for acme.

- name: 'Manage users | confirm user exists'
  ansible.builtin.command: 'id {{ acme_user }}'
  register: _acme_user_exists
  changed_when: _acme_user_exists.rc > 0
  failed_when: false

- name: 'Manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ acme_group }}'
  register: _acme_group_exists
  changed_when: _acme_group_exists.rc > 0
  failed_when: false

- name: 'Manage users | create acme group'
  ansible.builtin.group:
    name: '{{ acme_default_group.name }}'
    gid: '{{ acme_default_group.gid }}'
    state: 'present'
  when: acme_create_user and _acme_group_exists.rc != 0

- name: 'Manage users | create acme user (logins disabled)'
  ansible.builtin.user:
    name: '{{ acme_default_user.name }}'
    group: '{{ acme_default_user.group }}'
    groups: '{{ acme_default_user.groups }}'
    uid: '{{ acme_default_user.uid }}'
    shell: '{{ acme_default_user.shell }}'
    home: '{{ acme_default_user.home }}'
    create_home: '{{ acme_default_user.create_home }}'
    password: '{{ acme_default_user.password }}'
    password_lock: '{{ acme_default_user.password_lock }}'
    update_password: '{{ acme_default_user.update_password }}'
    expires: '{{ acme_default_user.expires }}'
    system: '{{ acme_default_user.system }}'
    state: 'present'
  when: acme_create_user and _acme_user_exists.rc != 0
