---
###############################################################################
# ACME Handlers
###############################################################################

- name: 'reload systemd'
  ansible.builtin.systemd:
    daemon-reload: true

- name: 'restart dnsrobocert'
  ansible.builtin.systemd:
    name: 'dnsrobocert'
    enabled: true
    state: 'restarted'
